# Generated by Django 3.0.5 on 2020-04-08 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categories', models.CharField(choices=[('HOBB', 'Áhugamál'), ('BOOK', 'Bókamerki'), ('NEWS', 'Fréttir'), ('SPOR', 'Íþróttir'), ('GAME', 'Leikir'), ('EDUC', 'Nám'), ('SOCI', 'Samfélagsmiðlar'), ('SHOP', 'Versla'), ('WORK', 'Vinna'), ('FAVO', 'Uppáhald')], default='FAVO', max_length=4)),
                ('name', models.CharField(max_length=32)),
                ('img', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('order_no', models.IntegerField(default=-1)),
                ('clicks', models.IntegerField(default=0)),
                ('_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
