# Generated by Django 3.0.5 on 2020-04-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topsites',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
