# Generated by Django 3.0.5 on 2020-04-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_auto_20200408_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topsites',
            name='order_no',
        ),
        migrations.AlterField(
            model_name='topsites',
            name='categories',
            field=models.CharField(choices=[('HOBB', 'Áhugamál'), ('BOOK', 'Bókamerki'), ('NEWS', 'Fréttir'), ('SPOR', 'Íþróttir'), ('GAME', 'Leikir'), ('EDUC', 'Nám'), ('SOCI', 'Samfélagsmiðlar'), ('SHOP', 'Versla'), ('WORK', 'Vinna'), ('FAVO', 'Uppáhalds')], default='FAVO', max_length=4),
        ),
    ]
