# Generated by Django 3.0.5 on 2020-04-12 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0003_auto_20200412_0206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topsites',
            old_name='_userid',
            new_name='_user',
        ),
    ]
